// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddProfileFromClipboard():Promise<void>;

export function CopyVLESS(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function GetProfiles():Promise<Array<backend.Profile>>;

export function GetTrafficStats():Promise<Record<string, number>>;

export function StartProfile(arg1:string):Promise<void>;

export function StopProfile():Promise<void>;
