// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddProfileFromClipboard():Promise<void>;

export function GetProfiles():Promise<Array<main.Profile>>;

export function StartProfile(arg1:string):Promise<void>;

export function StopProfile():Promise<void>;
